services:
  postgres:
    image: postgres:15
    container_name: auth_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
